finance_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dev_finance
      threads: 4
      timeout_seconds: 300
      location: US

    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: prod_finance
      threads: 4
      timeout_seconds: 300
      location: US